services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # donne l'accès à Docker
    user: root # Important pour avoir les droits sudo/Docker

volumes:
  jenkins_home:
